export const employees = [
    {
        id: '1',
        name: 'John Doe',
        joiningDate: '15-Jan-2023',
        role: 'Software Engineer',
        status: 'Active',
        experience: '3 Years',
        address: 'xyz',
    },
    {
        id: '2',
        name: 'Jane Smith',
        joiningDate: '22-Mar-2022',
        role: 'QA Engineer',
        status: 'Probation',
        experience: '4 Years',
        address: 'xyz',
    },
    {
        id: '3',
        name: 'Michael Brown',
        joiningDate: '10-Aug-2021',
        role: 'DevOps Engineer',
        status: 'Inactive',
        experience: '5 Years',
        address: 'xyz',
    },
    {
        id: '4',
        name: 'Sarah Wilson',
        joiningDate: '05-Jun-2024',
        role: 'Product Manager',
        status: 'Probation',
        experience: '1 Year',
        address: 'xyz',
    },
    {
        id: '5',
        name: 'David Lee',
        joiningDate: '18-Nov-2020',
        role: 'UI/UX Designer',
        status: 'Active',
        experience: '6 Years',
        address: 'xyz',
    },
    {
        id: '6',
        name: 'Emily Johnson',
        joiningDate: '12-Feb-2023',
        role: 'Frontend Developer',
        status: 'Inactive',
        experience: '2 Years',
        address: 'xyz',
    },
    {
        id: '7',
        name: 'Robert Garcia',
        joiningDate: '30-Sep-2022',
        role: 'Backend Developer',
        status: 'Active',
        experience: '3 Years',
        address: 'xyz',
    },
    {
        id: '8',
        name: 'Sophia Martinez',
        joiningDate: '18-Apr-2025',
        role: 'Business Analyst',
        status: 'Probation',
        experience: '6 Months',
    },
    {
        id: '9',
        name: 'William Anderson',
        joiningDate: '14-Jul-2021',
        role: 'System Administrator',
        status: 'Inactive',
        experience: '5 Years',
    },
    {
        id: '10',
        name: 'Olivia Thomas',
        joiningDate: '09-Jan-2024',
        role: 'Data Engineer',
        status: 'Active',
        experience: '2 Years',
    },
];
